local MonsterConfig = {}

-- displayName, level, hp, damage, attackSpeed (sec), aggroRadius, xpReward, lootTable, color, scale
MonsterConfig.Monsters = {
	giant_rat = {
		displayName = "Giant Rat",
		level = 2,
		hp = 60,
		damage = 6,
		attackSpeed = 1.6,
		aggroRadius = 18,
		xpReward = 25,
		lootTable = "low_critter",
		color = Color3.fromRGB(120, 90, 70),
		scale = 0.8,
	},
	wild_boar = {
		displayName = "Wild Boar",
		level = 5,
		hp = 140,
		damage = 12,
		attackSpeed = 1.8,
		aggroRadius = 22,
		xpReward = 60,
		lootTable = "low_critter",
		color = Color3.fromRGB(80, 60, 50),
		scale = 1.1,
	},
	bandit = {
		displayName = "Freeport Bandit",
		level = 10,
		hp = 280,
		damage = 22,
		attackSpeed = 1.5,
		aggroRadius = 26,
		xpReward = 140,
		lootTable = "mid_humanoid",
		color = Color3.fromRGB(60, 60, 80),
		scale = 1.0,
	},
	orc_warrior = {
		displayName = "Orc Warrior",
		level = 18,
		hp = 600,
		damage = 38,
		attackSpeed = 1.6,
		aggroRadius = 28,
		xpReward = 320,
		lootTable = "mid_humanoid",
		color = Color3.fromRGB(70, 110, 60),
		scale = 1.25,
	},
	skeletal_knight = {
		displayName = "Skeletal Knight",
		level = 28,
		hp = 1200,
		damage = 65,
		attackSpeed = 1.7,
		aggroRadius = 30,
		xpReward = 700,
		lootTable = "elite",
		color = Color3.fromRGB(220, 220, 200),
		scale = 1.3,
	},
	dragon_whelp = {
		displayName = "Dragon Whelp",
		level = 35,
		hp = 2200,
		damage = 95,
		attackSpeed = 1.4,
		aggroRadius = 35,
		xpReward = 1400,
		lootTable = "elite",
		color = Color3.fromRGB(180, 60, 50),
		scale = 1.4,
	},
	fire_drake = {
		displayName = "Fire Drake",
		level = 45,
		hp = 5000,
		damage = 160,
		attackSpeed = 1.4,
		aggroRadius = 40,
		xpReward = 3200,
		lootTable = "elite",
		color = Color3.fromRGB(220, 80, 30),
		scale = 1.7,
	},
	ancient_dragon = {
		displayName = "Vexrothan, the Ancient",
		level = 50,
		hp = 60000,
		damage = 320,
		attackSpeed = 1.2,
		aggroRadius = 80,
		xpReward = 25000,
		lootTable = "dragon_hoard",
		color = Color3.fromRGB(180, 30, 30),
		scale = 4.0,
		isBoss = true,
		isRaidBoss = true,
	},
}

function MonsterConfig.Get(id)
	return MonsterConfig.Monsters[id]
end

return MonsterConfig
